[project]
name = "imdb-clean-ds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "polars>=1.30.0",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
